# Created first deployment using CloudFormation
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  "This is the EC2 instance to deploy in us-west-2 region 
    Allocate an Elastic IP address " 
Parameters: 
  InstanceType:
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  
  NetworkStack:
    Type: String
    Description: The subnet ID
    Default: SampleNetworkCrossStack

  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: key-us-west-2
    
  
Mappings: 
  DeployRegionMap: # Region Map por Map Name
    us-west-2:
      "HVM64": "ami-094125af156557ca2"
    us-east-1: # Top Level Key
      "HVM64": "ami-0b0dcb5067f052a63"   # Second Level Key 
    us-west-1: 
      "HVM64": "ami-0f5e8a042c8bfcd5e"
    eu-west-1: 
      "HVM64": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "HVM64": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "HVM64": "ami-06cd52961ce9f0d85"

Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [DeployRegionMap,!Ref "AWS::Region", "HVM64" ]
      Tags: 
        - Key: "Name"
          Value: "Webserver"

      KeyName: 
        Ref: KeyName

      SecurityGroupIds: # we reference output from the export value of another stack.
        - Fn::ImportValue:
            !Sub "${NetworkStack}-SecurityGroupID" 
      SubnetId:
        Fn::ImportValue:
            !Sub "${NetworkStack}-SubnetID"  

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Welcome to Aman Business Solution Webpage" > /var/www/html/index.html

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2Instance

Outputs:
  PrivateSubnet: 
    Description: This output displays the private IPv4
    Value: !GetAtt Ec2Instance.PrivateIp
  DNSName:
    Description: This output displays the DNS Name
    Value: !GetAtt Ec2Instance.PublicDnsName
        


